# Site settings
title: "Wilderhood: Official Blog"
header-img: img/Launch.jpg
email: contact@wilderhood.com
description: "Travel community for wildlife destinations"
baseurl: ""

domainurl: http://blog.wilderhood.com
url: "http://blog.wilderhood.com"
#url: "http://127.0.0.1:4000"
twitter_username: https://twitter.com/wilderhood
github_username1:  https://github.com/wilderhood
facebook_username:  https://www.facebook.com/wilderhood
#googleplay_name: http://bit.ly/whoodplaystore
#iosappstore_name: http://bit.ly/whooditunes
disqus-shortname: wilderhood-Blog
domain-home: "wilderhood.com"

# Build settings
markdown: kramdown
highlighter: pygments
# permalink: pretty
relative_permalinks: false
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-sitemap